apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ashish
spec:
 acme:
   server: https://acme-v02.api.letsencrypt/org/directory
   email: hello2ashu@gmail.com
   privateKeySecretRef:
     name: letsencrypt-ashish
   solvers: 
   - http01:
       ingress:
         class: nginx
